---
# Raspberry Pi configuration.
drupal_pi_processor_count: 4
drupal_pi_app_directory: /opt/drupal-pi

# Security configuration.
security_sudoers_passwordless: ['pi']
firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443

# Drupal configuration.
drupal_url: www.drupalpi.test
drupal_docker_image: 'geerlingguy/drupal:latest-arm32v7'
drupal_files_directory_host: /var/drupal/files
drupal_files_directory_container: /var/www/html/sites/default/files
drupal_files_directory_owner: 33
drupal_database_password: supersecure
drupal_hash_salt: JcWFc2Z29LQIAeorS0IL9qB4SxOCjiYMd909AM3E2U
drupal_account_name: admin
drupal_account_pass: admin
drupal_download_if_not_present: 'true'

# MySQL configuration.
mysql_docker_image: 'hypriot/rpi-mysql:5.5'
mysql_root_password: rootpasswordhere

# Nginx configuration.
nginx_worker_processes: "{{ drupal_pi_processor_count }}"
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []
nginx_proxy_pass: http://127.0.0.1:8080/
nginx_access_log: "off"

# Nginx load balancing configuration (disabled by default).
nginx_use_as_lb: false
nginx_lb_backends:
  - '10.0.100.62'
  - '10.0.100.63'
  - '10.0.100.64'
