---
# Raspberry Pi configuration.
drupal_pi_processor_count: 4

# Security configuration.
security_sudoers_passwordless: ['pi']
firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443

# Drupal configuration.
drupal_database_password: supersecure
drupal_account_name: admin
drupal_account_pass: admin

# Nginx configuration.
nginx_worker_processes: "{{ drupal_pi_processor_count }}"
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []
nginx_access_log: "off"
