---
- hosts: pi
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

    - name: Include hook-pre-tasks.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - hook-pre-tasks.yml
          skip: true

    - import_tasks: tasks/init.yml

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.docker_arm

  tasks:
    - name: Include hook-tasks.yml if it exists.
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - hook-tasks.yml
          skip: true

    - import_tasks: tasks/docker-compose-setup.yml

    - name: Copy vhost configuration into place.
      template:
        src: templates/drupal.conf.j2
        dest: /etc/nginx/sites-enabled/drupal.conf
        mode: 0644
      notify: restart nginx
