---
- hosts: pi
  sudo: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include: tasks/wheezy-backports.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - name: Copy vhost configuration into place.
      template:
        src: templates/drupal.conf.j2
        dest: /etc/nginx/sites-enabled/drupal.conf
        mode: 0644
      notify: restart nginx

    - name: Copy php5-fpm www pool configuration into place.
      template:
        src: templates/www.conf.j2
        dest: /etc/php5/fpm/pool.d/www.conf
        mode: 0644
      notify: restart php-fpm

    - name: Ensure dependencies are installed.
      apt: "name={{ item }} state=present"
      with_items:
        # Needed to complete Drupal installation.
        - sendmail-bin
        - sendmail
        # So drush can connect to MySQL.
        - mysql-client
        # For boris (drush requirement that uses missing php5-readline package).
        - libedit-dev

    - include: tasks/drupal.yml
