---
- hosts: pi
  become: yes

  vars_files:
    - config.yml

  pre_tasks:
    - name: Include source install vars if configured.
      include_vars: vars/source-install.yml
      when: pi_install_php_from_source

    - include: tasks/init.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - { role: "geerlingguy.php-mysql", when: "not pi_install_php_from_source" }
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.security

  tasks:
    - name: Copy vhost configuration into place.
      template:
        src: templates/drupal.conf.j2
        dest: /etc/nginx/sites-enabled/drupal.conf
        mode: 0644
      notify: restart nginx

    - name: Ensure dependencies are installed.
      apt: "name={{ item }} state=present"
      with_items:
        # Needed to complete Drupal installation.
        - sendmail-bin
        - sendmail
        # So drush can connect to MySQL.
        - mysql-client
        # For some flavors of Debian without cron installed by default.
        - cron

    - include: tasks/drupal.yml
