---
- hosts: pi
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

    - name: Include source install vars if configured.
      include_vars: vars/source-install.yml
      when: pi_install_php_from_source

    - import_tasks: tasks/init.yml

  roles:
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - role: geerlingguy.php-mysql
      when: not pi_install_php_from_source
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal

  tasks:
    - name: Copy vhost configuration into place.
      template:
        src: templates/drupal.conf.j2
        dest: /etc/nginx/sites-enabled/drupal.conf
        mode: 0644
      notify: restart nginx
