---
- hosts: pi
  become: yes

  vars_files:
    - config.yml

  tasks:
    - name: Ensure Drupal site codebase is removed.
      file:
        path: "{{ drupal_core_path }}"
        state: absent
      notify: restart services

    - name: Ensure Drupal database is dropped.
      mysql_db:
        name: drupal
        state: absent
      notify: restart services

    - name: Test.
      command: "which git"
      notify: restart services

  handlers:
    - name: restart services
      service: "name={{ item }} state=restarted"
      with_items:
        - nginx
        - "{{ 'php-fpm' if pi_install_php_from_source else 'php7.0-fpm' }}"
        - mysql
