---
- name: Check if Drupal is already set up.
  stat: "path={{ drupal_core_path }}/index.php"
  register: drupal_site

- name: Set a shell for www-data user.
  user: name=www-data shell=/bin/bash

- name: Ensure /var/www directory exists.
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Ensure drupal_core_path exists.
  file:
    path: "{{ drupal_core_path }}"
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

# Generate Drupal codebase with makefile.
- name: Copy drush makefile into place.
  copy:
    src: "{{ drush_makefile_path }}"
    dest: /tmp/drupal.make.yml
  when: drupal_site.stat.exists == false

- name: Generate Drupal site with drush makefile.
  command: >
    {{ drush_path }} make -y /tmp/drupal.make.yml
    chdir={{ drupal_core_path }}
  when: drupal_site.stat.exists == false

# Install Drupal if not already installed.
- name: Check if site is already installed.
  command: >
    {{ drush_path }} status bootstrap
    chdir={{ drupal_core_path }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false

- name: Install Drupal dependencies with Composer.
  command: >
    composer install
    chdir={{ drupal_core_path }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"

- name: Install Drupal with drush.
  command: >
    {{ drush_path }} site-install standard -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ mysql_users[0].name }}:{{ mysql_users[0].password }}@localhost/{{ mysql_databases[0].name }}
    chdir={{ drupal_core_path }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"

- name: Fix file permissions on Drupal folders after install.
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    owner: www-data
    group: www-data
    state: directory
    recurse: true
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"

- name: Add Drupal cron job.
  cron:
    name: "Drupal Pi cron"
    minute: "*/15"
    user: "{{ ansible_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
    job: "/usr/local/bin/drush --quiet --root={{ drupal_core_path }} cron -y"
