---
- name: Update apt cache if needed.
  apt: update_cache=true cache_valid_time=86400

- name: Ensure /usr/local/bin exists.
  file:
    path: /usr/local/bin
    state: directory
    mode: 0775

- name: Ensure auth.log file is present.
  copy:
    dest: /var/log/auth.log
    content: ""
    force: false

- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - openssh-server
      - openssh-client
      - libffi-dev
      - libssl-dev
      - python-backports.ssl-match-hostname
      # For some flavors of Debian without cron installed by default.
      - cron
    state: present

- name: Override Drupal Docker image if not on ARM and default is set.
  set_fact:
    drupal_docker_image: 'geerlingguy/drupal:latest'
  when:
    - ansible_architecture is not search('arm')
    - drupal_docker_image == 'geerlingguy/drupal:latest-arm32v7'

- name: Override MySQL Docker image if not on ARM and default is set.
  set_fact:
    mysql_docker_image: 'mysql/mysql-server:8.0'
  when:
    - ansible_architecture is not search('arm')
    - mysql_docker_image == 'hypriot/rpi-mysql:5.5'
