---
- name: Update apt cache if needed.
  apt: update_cache=true cache_valid_time=86400

- name: Ensure /usr/local/bin exists.
  file:
    path: /usr/local/bin
    state: directory
    mode: 0775

- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - openssh-server
      - openssh-client
      # Needed to complete Drupal installation.
      - sendmail-bin
      - sendmail
      # For some flavors of Debian without cron installed by default.
      - cron
    state: present
