---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure /usr/local/bin exists.
  file:
    path: /usr/local/bin
    state: directory
    mode: 0775

- name: Ensure curl is present.
  apt: name=curl state=present
