---
- name: Ensure apt cache has been updated recently.
  apt: update_cache=yes cache_valid_time=86400

- name: Add wheezy-backports apt source.
  apt_repository:
    repo: 'deb http://http.debian.net/debian wheezy-backports main'
    state: present
  register: wheezy_backports

- name: Add wheezy-backports apt key.
  apt_key:
    keyserver: pgpkeys.mit.edu
    id: 8B48AD6246925553
    state: present
  when: wheezy_backports.changed

- name: Update apt cache.
  apt: update_cache=yes
  when: wheezy_backports.changed
