---
- name: Ensure apt cache has been updated recently.
  apt: update_cache=yes cache_valid_time=86400

- name: Add wheezy-backports apt source.
  apt_repository:
    repo: 'deb http://http.debian.net/debian wheezy-backports main'
    state: present
  register: wheezy_backports

- name: Add wheezy-backports apt keys.
  apt_key:
    keyserver: pgpkeys.mit.edu
    id: "{{ item }}"
    state: present
  when: wheezy_backports.changed
  with_items:
    - 8B48AD6246925553
    - 7638D0442B90D010

- name: Update apt cache.
  apt: update_cache=yes
  when: wheezy_backports.changed
